In [1]:
import numpy as np

# 1. Create a NumPy array containing numbers from 1 to 15
arr1 = np.arange(1, 16)
print("Q1:", arr1)



Q1: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [2]:

# 2. Create a 5×5 matrix of all zeros
zeros_matrix = np.zeros((5, 5))
print("\nQ2:\n", zeros_matrix)



Q2:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:

# 3. Create an array of 10 random integers between 50 and 100
rand_ints = np.random.randint(50, 101, size=10)
print("\nQ3:", rand_ints)




Q3: [56 93 50 56 89 74 59 62 94 57]


In [4]:
# 4. Create a 1D array from 1 to 20 and extract parts
arr2 = np.arange(1, 21)
print("\nQ4a First 5:", arr2[:5])
print("Q4b Last 4:", arr2[-4:])
print("Q4c Index 3 to 10:", arr2[3:11])


Q4a First 5: [1 2 3 4 5]
Q4b Last 4: [17 18 19 20]
Q4c Index 3 to 10: [ 4  5  6  7  8  9 10 11]


In [5]:
#Indexing & Slicing

In [6]:
# 5. Matrix operations
mat = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print("\nQ5a Element 50:", mat[1, 1])
print("Q5b First two rows:\n", mat[:2, :])
print("Q5c Last column:\n", mat[:, -1])



Q5a Element 50: 50
Q5b First two rows:
 [[10 20 30]
 [40 50 60]]
Q5c Last column:
 [30 60 90]


In [7]:

# 6. Extract all elements greater than 20
arr3 = np.array([5, 10, 15, 20, 25, 30, 35])
print("\nQ6 Elements > 20:", arr3[arr3 > 20])



Q6 Elements > 20: [25 30 35]


In [8]:
#Operations

In [9]:
# 7. Arithmetic
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])
print("\nQ7a Addition:", a + b)
print("Q7b Subtraction:", a - b)
print("Q7c Multiplication:", a * b)
print("Q7d Division:", a / b)
print("Q7e Multiply a by 5:", a * 5)





Q7a Addition: [ 3  7 11 15]
Q7b Subtraction: [1 1 1 1]
Q7c Multiplication: [ 2 12 30 56]
Q7d Division: [2.         1.33333333 1.2        1.14285714]
Q7e Multiply a by 5: [10 20 30 40]


In [10]:
# 8. Math functions
arr4 = np.array([1, 4, 9, 16, 25])
print("\nQ8a Square root:", np.sqrt(arr4))
print("Q8b Logarithm:", np.log(arr4))
print("Q8c Sine values:", np.sin(arr4))


Q8a Square root: [1. 2. 3. 4. 5.]
Q8b Logarithm: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Q8c Sine values: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
