In [2]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)



1D Array: [1 2 3 4 5]


In [3]:

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)




2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# Zeros, Ones, and Range
zeros_arr = np.zeros((3, 3))
ones_arr = np.ones((2, 4))
range_arr = np.arange(0, 20, 2)

print("\nZeros:\n", zeros_arr)
print("\nOnes:\n", ones_arr)
print("\nRange Array:", range_arr)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Range Array: [ 0  2  4  6  8 10 12 14 16 18]


In [6]:
# Array Indexing & Slicing

arr = np.arange(10, 20)
print("Original Array:", arr)

# Slicing
print("First 5 elements:", arr[:5])
print("Last 3 elements:", arr[-3:])
print("Elements from index 2 to 7:", arr[2:8])



Original Array: [10 11 12 13 14 15 16 17 18 19]
First 5 elements: [10 11 12 13 14]
Last 3 elements: [17 18 19]
Elements from index 2 to 7: [12 13 14 15 16 17]


In [7]:
# 2D Slicing
mat = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("\n2D Matrix:\n", mat)
print("Element at [1,2]:", mat[1, 2])
print("First 2 rows:\n", mat[:2, :])
print("First 2 columns:\n", mat[:, :2])




2D Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at [1,2]: 60
First 2 rows:
 [[10 20 30]
 [40 50 60]]
First 2 columns:
 [[10 20]
 [40 50]
 [70 80]]


In [9]:
#Array Operations
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Arithmetic
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]


In [10]:

# Scalar operations
print("Multiply by 10:", a * 10)


Multiply by 10: [10 20 30 40]


In [11]:
#  Mathematical Functions
arr = np.array([1, 4, 9, 16, 25])

print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr))
print("Sine values:", np.sin(arr))


Square root: [1. 2. 3. 4. 5.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Logarithm: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Sine values: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
