In [3]:
import numpy as np
# Reshaping & Stacking

In [4]:
# 9. Reshape array
arr5 = np.arange(1, 13).reshape(3, 4)
print("\nQ9 Reshaped 3x4:\n", arr5)




Q9 Reshaped 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# 10. Stack arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print("\nQ10a Vertical Stack:\n", np.vstack((x, y)))
print("Q10b Horizontal Stack:\n", np.hstack((x, y)))



Q10a Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Q10b Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [6]:
# Random & Statistics

In [7]:
# 11. Statistics
data = np.random.randint(1, 51, size=20)
print("\nQ11 Data:", data)
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Max:", np.max(data))
print("Min:", np.min(data))



Q11 Data: [ 1 19 15 25  3 22 32 15 31  7 24 15 13  7 31 21  4 17 42 14]
Mean: 17.9
Median: 16.0
Standard Deviation: 10.587256490706174
Max: 42
Min: 1


In [8]:

# 12. Sum of each row
rand_mat = np.random.randint(1, 11, size=(3, 3))
print("\nQ12 Matrix:\n", rand_mat)
print("Sum of each row:", np.sum(rand_mat, axis=1))



Q12 Matrix:
 [[ 1  5  1]
 [ 2  9  2]
 [ 2 10  1]]
Sum of each row: [ 7 13 13]


In [9]:

# 12. Sum of each row
rand_mat = np.random.randint(1, 11, size=(3, 3))
print("\nQ12 Matrix:\n", rand_mat)
print("Sum of each row:", np.sum(rand_mat, axis=1))



Q12 Matrix:
 [[ 2 10  7]
 [ 8  2  7]
 [ 4  1  3]]
Sum of each row: [19 17  8]
