In [3]:
import numpy as np
#Reshaping & Flattening
arr = np.arange(1, 13)
print("Original:", arr)


Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:

reshaped = arr.reshape(3, 4)
print("\nReshaped 3x4:\n", reshaped)





Reshaped 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
flattened = reshaped.flatten()
print("\nFlattened:", flattened)


Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
#  Stacking & Splitting
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stacking
print("Vertical Stack:\n", np.vstack((a, b)))
print("Horizontal Stack:\n", np.hstack((a, b)))




Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [7]:
# Splitting
arr = np.arange(1, 10)
print("Split into 3 parts:", np.split(arr, 3))

Split into 3 parts: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [1]:
# Random numbers 

In [4]:
print("Random Float [0,1):", np.random.rand(5))
print("Random Integers:", np.random.randint(10, 50, size=(3, 3)))

# Random with normal distribution
print("Normal Distribution:\n", np.random.randn(4, 4))


Random Float [0,1): [0.04046686 0.93988313 0.21521358 0.93911847 0.32125983]
Random Integers: [[16 17 25]
 [46 14 24]
 [21 18 20]]
Normal Distribution:
 [[ 0.91421296  0.17058921 -1.80075122 -1.1217139 ]
 [-0.22540077 -0.51169021 -1.54927101  0.10574016]
 [ 0.94545173  0.47294431  1.03512483  1.23863801]
 [-1.2519669  -0.46095575 -0.80568859 -0.44225414]]


In [5]:
# stastics with numpy

In [6]:
data = np.random.randint(1, 100, size=10)
print("Data:", data)

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Sum:", np.sum(data))
print("Max:", np.max(data))
print("Min:", np.min(data))


Data: [31 35 32 57  4 95 97 66  3 61]
Mean: 48.1
Median: 46.0
Standard Deviation: 31.39888533053363
Sum: 481
Max: 97
Min: 3


In [7]:
# BOOLEAN INDEXING 

In [8]:
arr = np.arange(1, 11)
print("Original:", arr)

print("Greater than 5:", arr[arr > 5])
print("Even numbers:", arr[arr % 2 == 0])


Original: [ 1  2  3  4  5  6  7  8  9 10]
Greater than 5: [ 6  7  8  9 10]
Even numbers: [ 2  4  6  8 10]


In [9]:
# Broadcasting Example

In [ ]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Matrix:\n", mat)

# Adding a scalar
print("Add 10:\n", mat + 10)



Original Matrix:
 [[1 2 3]
 [4 5 6]]
Add 10:
 [[11 12 13]
 [14 15 16]]
Add row vector:
 [[11 22 33]
 [14 25 36]]


In [11]:
# Broadcasting a row vector
row_vector = np.array([10, 20, 30])
print("Add row vector:\n", mat + row_vector)


Add row vector:
 [[11 22 33]
 [14 25 36]]
