In [3]:
import numpy as np 
# 16. Identity matrix
identity = np.eye(5)
print("\nQ16 Identity Matrix:\n", identity)


Q16 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
# 17. Diagonal matrix
diag_matrix = np.diag([10, 20, 30, 40, 50])
print("\nQ17 Diagonal Matrix:\n", diag_matrix)


Q17 Diagonal Matrix:
 [[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [ ]:
# 18. Reverse array
arr8 = np.arange(1, 11)
print("\nQ18 Reverse:", arr8[::-1])



Q18 Reverse: [10  9  8  7  6  5  4  3  2  1]


In [ ]:
# 19. Replace even numbers with -1
arr9 = np.arange(1, 11)
arr9[arr9 % 2 == 0] = -1
print("Q19 Replace even numbers with -1:", arr9)


Q19 Replace even numbers with -1: [ 1 -1  3 -1  5 -1  7 -1  9 -1]


In [ ]:
# 20. Sum of diagonal elements
mat3 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("\nQ20 Sum of diagonal:", np.trace(mat3))


Q20 Sum of diagonal: 15
